### ISSUE TITLE
IE rendering mode

### ISSUE THREAD

**Issue by kczx3** [G33kDude/Neutron.ahk#1]
https://github.com/G33kDude/Neutron.ahk/blob/d14cb9928e7404a462cc42c96a588dea08265259/Neutron.ahk#L251

I'm curious, what compatability issues does the meta tag not solve?

**Comment by G33kDude** [comment]
Nothing major I can think of off the top of my head, but including that tag seems to make the document exit quirks mode, meaning that some older non-standard markup is no longer accepted in favor of the new standardized markup (e.g. CSS `cursor: hand` no longer works, replaced by `cursor: pointer`). I figure if there's something like that I can see, there's probably a lot more like that I can't/didn't see. Further, using just the meta tag doesn't address the issue of, say, embedding external content in an iframe / navigating to external content, where that content doesn't contain the meta tag and the user cannot control it directly.

Something else not noted there, using just the registry isn't enough either. When you compile a Neutron script, it switches from using file URLs to using res:// URLs, to load content from the EXE resources. When loading a res:// URL, the registry key appears to be ignored. I am not sure if this is a bug on Microsoft's part or just an undocumented "feature", but it's there nonetheless.

To provide the widest compatibility for pages I use both techniques.

**Comment by kczx3** [comment]
Interesting.  Hadn't considered the resource URL might be handled differently.  Some software I support uses resource URLs in their application that uses many WebBrowser controls.  Its a feature I was fairly unfamiliar with.  Don't see it a whole lot.

That was a great find by you to use FileInstall to bundle the assets but not have them output to disk when the script is ran.  Genius!
