### ISSUE TITLE
Plans to update engine?

### ISSUE THREAD

**Issue by dpalay** [G33kDude/Neutron.ahk#10]
Are there any plans to move this to the chromium engine instead of the trident? Or webview2? 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by G33kDude** [comment]
This library will not move away from Trident, but the WebView2 version, called Positron.ahk, is under development. Ping me on Discord if you would a beta copy to play with

**Comment by SaifAqqad** [comment]
> Positron.ahk
👀 I'm definitely interested in said beta copy

**Comment by dpalay** [comment]
Same.  I'll reach out in discord
