### ISSUE TITLE
Select All, Cut, Copy and Paste keyboard shortcuts don't work

### ISSUE THREAD

**Issue by SynnKo** [G33kDude/Neutron.ahk#11]
I don't know if this is an issue with HTML in AutoHotkey in general, but I found out that if you attempt to do any actions that are tied to CTRL (see title) it won't do anything. I can still right click and do those actions from the context menu, but the keyboard shortcuts don't seem to work.

Is this a common issue? I really want to use Neutron, but not being able to use those keyboard shortcuts is a huge drawback.

I don't know if this will be helpful, but I'm on Windows 10 and my main browser is Brave.

**Comment by G33kDude** [comment]
Fixed by commit e8f9ec58, will be working in next release

**Comment by SynnKo** [comment]
Thank you for the quick response! I just tried it and it works perfectly. When is the next release?

**Comment by G33kDude** [comment]
Current development is going toward my new JSON library, then Chrome.ahk is next on the list. Once those are clear, I intend to write a new demo using Semantic UI with Neutron and then I'll push a release. ETA is probably like 4 months, but please don't hold me to that.

**Comment by SynnKo** [comment]
So it's going to take a while... that's ok, I'll just using the fix from that commit to move my own project along and update it later when the new official release is up. Thank you for pointing me to the right commit!
