### ISSUE TITLE
Using HTML Button To Load Website In Chrome?

### ISSUE THREAD

**Issue by jayfinley** [G33kDude/Neutron.ahk#14]
With the bootstrap example how could i use a button to load a website inside google chrome?

Something like this, not sure if this can be done using Neutron.

chrome.exe "https://mail.google.com/" " --new-window "

`       <button type="button" onclick="ahk.Button(event)" class="btn btn-block btn-outline-primary">Block level
            button</button>`

Thanks

**Comment by SaifAqqad** [comment]
[Using the `Run` command in AHK](https://www.autohotkey.com/docs/commands/Run.htm)

```ahk
Run, chrome.exe "https://mail.google.com/" "--new-window "
```
If you just need to open the site in the default browser you can just run the url alone
```ahk
Run, https://mail.google.com/
```

**Comment by jayfinley** [comment]
Thanks :-)
