### ISSUE TITLE
Keyboard accelerator handling

### ISSUE THREAD

**Issue by kczx3** [G33kDude/Neutron.ahk#2]
https://github.com/G33kDude/Neutron.ahk/blob/d14cb9928e7404a462cc42c96a588dea08265259/Neutron.ahk#L382

As I did in the past, you copied the keyboard accelerator handling from the Autohotkey Installer.  Unfortunately, I don't think you read into it much.  The current settings make it impossible to copy, paste, cut, select all, and possibly others.

I've used the following string to allow those accelerators through:

`[B,D-U,W,Y-Z]`

**Comment by G33kDude** [comment]
Yeah, the accelerator handler is definitely sub-optimal, but I figured it was fine for the big `1.0.0`. I'll look into your suggestion, thanks!
