### ISSUE TITLE
how to get / set zoom level?

### ISSUE THREAD

**Issue by gittyup2018** [G33kDude/Neutron.ahk#23]
Hi, is it possible to get and/or set the zoom level?  I know it can be adjusted by the usual ctrl+mousewheel shortcuts but that doesn't save  or trigger any events. 

I found this code in the webapp.ahk (https://github.com/joedf/Webapp.ahk) and that has it's own zoom function but I can't even begin to understand how to convert it to Neutron as I'm a AHK noob..I've used it for years for re-mapping keys but never even played with a script or knew about GUI functions, etc

setZoomLevel(z) {
	global __Webapp_DPI_Aware
	
	; https://stackoverflow.com/a/738254/883015
	OLECMDID_OPTICAL_ZOOM := 63
	OLECMDID_OPTICAL_GETZOOMRANGE := 64
	OLECMDEXECOPT_DONTPROMPTUSER :=  2 ;?  https://social.msdn.microsoft.com/Forums/ie/en-US/21d2bc41-d182-4af6-81e9-6e06793058b9
	wb := getDOM()
	
	if (__Webapp_DPI_Aware) {
		DPI_Scale := A_ScreenDPI/96
		z := z * DPI_Scale
	}
	
	; ensure INT
	z := z & 0xFFFFFFFF
	
	wb.ExecWB( OLECMDID_OPTICAL_ZOOM, OLECMDEXECOPT_DONTPROMPTUSER, z, 0)
}

**Comment by G33kDude** [comment]
Replace `wb := getDOM()` with `wb := this.wb` and add the function definition to the class,  then you should be able to call `myNeutronInstance.setZoomLevel(xyz)`

**Comment by gittyup2018** [comment]
wow I knew it was something easy, thanks! and thanks for quick reply!
