### ISSUE TITLE
how to disable resize window?

### ISSUE THREAD

**Issue by clownless** [G33kDude/Neutron.ahk#4]

**Comment by amerkestijn** [comment]
Bit late but i was looking for the same thing.
How i solved it in my case was by adding "Gui, -Resize" after the neutron.Gui, just like a normal Gui.
You will still have the cursors of resizing, but you can't actually resize.

**Comment by G33kDude** [comment]
Right now, `neutron.Gui("-Resize")` is the recommended way. This will leave the sizing cursors but will disable resizing. Full resizing disable support is planned for the next release.

**Comment by clownless** [comment]
Solved, thanks @G33kDude
