### ISSUE TITLE
Animations (Transitions) are Laggy 

### ISSUE THREAD

**Issue by KiddoV** [G33kDude/Neutron.ahk#7]
Good day GeekDude!
Just wondering why it is some time animation on Neutron is laggy comparing with the actual IE11 when it is using the same jquery animations (transitions). Specially, I am using OverlayScrollbar plugin to make custom scrollbar, It run very smooth on IE11 but it is a bit jumping on Neutron. (Should they are identical because Neutron use the same core as IE11?)
If it is OverlayScrollbar issue, when open web page on IE11 it would have been lagging too... So, I hope I can get the answer from you. 
Thanks!

**Comment by KiddoV** [comment]
@SaifAqqad sorry, but it doesn't help anything 🤷🏻‍♂️

**Comment by SaifAqqad** [comment]
Are you running the script compiled or not?
if not, you need to add the registry key for `AutoHotkey.exe` or whatever version your script is running on (like `AutoHotkeyU64.exe`)

you can do it from your script using `RegWrite`
```ahk
   key_dir:= "SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\"
   SplitPath, A_AhkPath, ahk_exe
   script_exe:= A_IsCompiled? A_ScriptName : ahk_exe
   RegWrite, REG_DWORD, HKCU, % key_dir . "FEATURE_GPU_RENDERING", % script_exe, 0x1
```

also try setting the `FEATURE_BROWSER_EMULATION` to IE11 (`0x2AF8`)
```ahk
   RegWrite, REG_DWORD, HKCU, % key_dir . "FEATURE_BROWSER_EMULATION", % script_exe, 0x2AF8
```

**Comment by KiddoV** [comment]
@SaifAqqad Feel like it helps a little bit. Can't tell. But thank you anyway!!!
